// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/darrior/gophermart/internal/service (interfaces: AccrualSystem)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_accrual.go -package=mocks github.com/darrior/gophermart/internal/service AccrualSystem
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/darrior/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualSystem is a mock of AccrualSystem interface.
type MockAccrualSystem struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualSystemMockRecorder
	isgomock struct{}
}

// MockAccrualSystemMockRecorder is the mock recorder for MockAccrualSystem.
type MockAccrualSystemMockRecorder struct {
	mock *MockAccrualSystem
}

// NewMockAccrualSystem creates a new mock instance.
func NewMockAccrualSystem(ctrl *gomock.Controller) *MockAccrualSystem {
	mock := &MockAccrualSystem{ctrl: ctrl}
	mock.recorder = &MockAccrualSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualSystem) EXPECT() *MockAccrualSystemMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockAccrualSystem) GetOrder(number string) (models.AccrualOrderState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", number)
	ret0, _ := ret[0].(models.AccrualOrderState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockAccrualSystemMockRecorder) GetOrder(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockAccrualSystem)(nil).GetOrder), number)
}
